runtime: python37

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  secure: always

- url: /google5acf6d2992c8237d.html
  static_files: google5acf6d2992c8237d.html
  upload: google5acf6d2992c8237d.html
  secure: always

- url: /.*
  script: main.application
  secure: always

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "client-secret.json"
  PROJECT_ID: "sympy-gamma-hrd"
