version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: app
    container_name: gamma_app
    volumes:
      - ./app/:/usr/src/app/app/
    ports:
      - "5000:5000"
      - "8082:8082"
      - "8083:8083"
    environment:
      - DATASTORE_EMULATOR_HOST=datastore:8081
      - DATASTORE_USE_PROJECT_ID_AS_APP_ID=true
      - PROJECT_ID=sympy-gamma-hrd
      - GAE_VERSION=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gamma.rule=Host(`gamma.iamit.in`)"
      - "traefik.http.routers.gamma.entrypoints=websecure"
      - "traefik.http.routers.gamma.tls.certresolver=myresolver"

    command: python manage.py runserver 0.0.0.0:5000

  datastore:
    image: google/cloud-sdk:latest
    container_name: gamma_datastore
    ports:
      - "8081:8081"
    environment:
      - CLOUDSDK_CORE_PROJECT=sympy-live-hrd
    command: gcloud beta emulators datastore start --host-port=0.0.0.0:8081

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=dtu.amit@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
